### ISSUE TITLE
Truffle compilation failed

### ISSUE THREAD

**Issue by itzhv14** [AltafMShaikh/Dream-Killers-Fake-Product-Detection-using-Blockchain-application#1]
DeclarationError: Undeclared identifier.
  --> project:/contracts/MyApp.sol:29:3:
   |
29 | 		owner = msg.sender;
   | 		^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/contracts/MyApp.sol:35:25:
   |
35 | 		require(msg.sender == owner, "Only owner is authorised to create a manufacturer!");
   | 		                      ^^^^^

,DeclarationError: Undeclared identifier. Did you mean "Manufacturer"?
  --> project:/contracts/MyApp.sol:37:28:
   |
37 | 		Manufacturer storage m = manufacturers[_address];
   | 		                         ^^^^^^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/contracts/MyApp.sol:41:8:
   |
41 | 		emit ManufacturerCreated(_name, _address);
   | 		     ^^^^^^^^^^^^^^^^^^^

,DeclarationError: Undeclared identifier. Did you mean "Manufacturer"?
  --> project:/contracts/MyApp.sol:46:11:
   |
46 | 		require(manufacturers[msg.sender].exists == true, "You are not a Manufacturer!");
   | 		        ^^^^^^^^^^^^^

,DeclarationError: Undeclared identifier. Did you mean "Product" or "productId"?
  --> project:/contracts/MyApp.sol:48:23:
   |
48 | 		Product storage p = products[productId];
   | 		                    ^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/contracts/MyApp.sol:59:8:
   |
59 | 		emit ProductCreated(productId-1, msg.sender);
   | 		     ^^^^^^^^^^^^^^

,DeclarationError: Undeclared identifier. Did you mean "Product" or "productId"?
  --> project:/contracts/MyApp.sol:65:10:
   |
65 | 		return products[_id];
   | 		       ^^^^^^^^

,DeclarationError: Undeclared identifier. Did you mean "Product" or "productId"?
  --> project:/contracts/MyApp.sol:70:23:
   |
70 | 		Product storage p = products[_id];
   | 		                    ^^^^^^^^

,DeclarationError: Undeclared identifier.
  --> project:/contracts/MyApp.sol:76:8:
   |
76 | 		emit OwnershipUpdated(_id, _newOwner);
   | 		     ^^^^^^^^^^^^^^^^

Compilation failed. See above.

**Comment by AltafMShaikh** [comment]
Hello Harshvivek,
I have done a change in code and solved the issue. Now you can compile and
get results.
Thank You.

**Comment by itzhv14** [comment]
Thanks
